### ISSUE TITLE
Cannot start server after fresh install

### ISSUE THREAD

**Issue by pedrocruzio** [Call-for-Code/cfc-covid-19-video-transcriber#3]
After successfully installing dependencies in a fresh environment, `python manage.py start` does not initialize the server. I get the following error:

```
(video-transcriber) Pedros-MacBook-Pro-3:cfc-covid-19-video-transcriber pedrocruz$ python manage.py start
/bin/sh: gunicorn: command not found
```

**Comment by DanCunnington** [comment]
did you run `pipenv install`? gunicorn is included in the [Pipfile](https://github.com/Call-for-Code/cfc-covid-19-video-transcriber/blob/master/Pipfile)

**Comment by pedrocruzio** [comment]
Yup! That’s the issue I had. In a fresh machine, after following steps for installation, it still says gunicorn isn’t installed

**Comment by DanCunnington** [comment]
Seems odd. It works for me as a fresh install:
```bash
virutalenv -p /usr/bin/python3 .
source bin/activate
git clone git@github.com:Call-for-Code/cfc-covid-19-video-transcriber.git
cd cfc-covid-19-video-transcriber
pipenv install
python manage.py start
[2020-03-30 10:42:29 +0100] [5939] [INFO] Starting gunicorn 19.7.1
[2020-03-30 10:42:29 +0100] [5939] [INFO] Listening at: http://0.0.0.0:3000 (5939)
[2020-03-30 10:42:29 +0100] [5939] [INFO] Using worker: sync
[2020-03-30 10:42:29 +0100] [5942] [INFO] Booting worker with pid: 5942
```

**Comment by pedrocruzio** [comment]
I’m using an Anaconda virtual environment so maybe that’s why. Will test later today.

**Comment by DanCunnington** [comment]
Should still work - within your anaconda environment you can check which pip is being used with 

`which pip` - make sure that corresponds to where you expect pip to be installed within the anaconda environment.

Then assuming that's ok, you could try running `pip install gunicorn`. Also, if you're running on linux check out https://docs.gunicorn.org/en/stable/install.html
